name: test
on: [push]
jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: >
          sudo apt -y install libcunit1 libcunit1-doc libcunit1-dev &&
          make &&
          src/tests/test
